name: explore
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.22.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  english_words: ^3.1.5

  google_sign_in: ^4.0.1+3
  #https://pub.dev/packages/flutter_facebook_login
  flutter_facebook_login: ^2.0.0
  ########## Access Firebase ##########
  cloud_firestore: ^0.11.0+2
  #https://pub.dev/packages/firebase_auth
  firebase_auth: ^0.11.1
  firebase_storage: ^3.0.0

  ########## Toast, Cache data local, Pick images, cache network image and parse data time ##########
  fluttertoast: ^3.0.4 #Toast, https://pub.dartlang.org/packages/fluttertoast
  shared_preferences: ^0.5.2 #Cache data local https://pub.dartlang.org/packages/shared_preferences
  image_picker: ^0.6.0+3 # Pick images https://pub.dartlang.org/packages/image_picker
  cached_network_image: ^0.8.0 # https://pub.dartlang.org/packages/cached_network_image
  intl: ^0.15.8 # https://pub.dartlang.org/packages/intl

  #widgets
  flutter_calendar: ^0.0.1 #https://github.com/apptreesoftware/flutter_calendar


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/products.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
